# Generated by Django 4.2.4 on 2023-08-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_vrf_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='vrf_token',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='токен'),
        ),
    ]
