# Generated by Django 4.2.4 on 2023-08-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('set_product_status', 'Can change the status of products')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
